Fix CUDA 11.5 tests by adding dependencies entries. (#443)
Nightly CI runs are failing for CUDA 11.5 because the `build` package list does not specify a matrix entry for CUDA 11.5. This adds the missing matrix entry.

See failure below:
```
ValueError: No matching matrix found in 'build' for: {'cuda': '11.5', 'arch': 'x86_64'}
```

https://github.com/rapidsai/rapids-cmake/actions/runs/5652925311/job/15313316122

Authors:
  - Bradley Dice (https://github.com/bdice)

Approvers:
  - Robert Maynard (https://github.com/robertmaynard)

URL: https://github.com/rapidsai/rapids-cmake/pull/443